runtime: php
env: flex

runtime_config:
  document_root: public


# Ensure we skip ".env", which is only for local development
skip_files:
  - .env

env_variables:
  # Put production environment variables here.
  APP_ENV: local   # or production
  APP_DEBUG: true # or false
  APP_LOG: errorlog
  APP_TIMEZONE: UTC #your timezone of choice
  APP_KEY: base64:kGtcA3GgY2t8e1A2kX3C3SyfA6pTkxsZlPtuBed9hFA=
  STORAGE_DIR: /tmp
  CACHE_DRIVER: database
  SESSION_DRIVER: database
  ## Set these environment variables according to your CloudSQL configuration.
  DB_CONNECTION: mysql
  DB_HOST: localhost
  DB_PORT: 3306
  DB_DATABASE: db_banhang
  DB_USERNAME: root
  DB_PASSWORD:
  DB_SOCKET: "/cloudsql/nhom4-ued:us-central1:banhang"

  QUEUE_DRIVER: database #in case you execute queued jobs

beta_settings:
  # for Cloud SQL, set this value to the Cloud SQL connection name,
  # e.g. "project:region:cloudsql-instance"
  cloud_sql_instances: "nhom4-ued:us-central1:banhang"
